#!/bin/bash
echo "🌐 LOGOS ECOSYSTEM - Vercel Access"
echo "=================================="
echo ""
echo "Production URL: https://logos-ecosystem.vercel.app"
echo "Dashboard: https://vercel.com/dashboard"
echo ""
echo "Commands:"
echo "  vercel               # Deploy preview"
echo "  vercel --prod        # Deploy production"
echo "  vercel domains       # Manage domains"
echo "  vercel env           # Manage environment"
echo "  vercel logs          # View logs"
echo ""
