# Backend Nixpacks Configuration

[phases.setup]
nixPkgs = ["nodejs-20_x", "postgresql"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx tsc --version",
  "npm run build || (echo 'Build failed. Running debug build...' && npm run build:debug)"
]

[start]
cmd = "npx prisma migrate deploy && npm start"